### ISSUE TITLE
Best practices rather than modular code development?

### ISSUE THREAD

**Issue by annefou** [coderefinery/modular-code-development#2]
Should we consider growing this lesson into a general “best practices” session?

Possible adds-on to the lesson:
- [x] pep8 (move here from IDE lesson),
- [x] coding style with guidelines on line length, script length, script organization, one class per module, etc..
- [x] coding framework such as testing, doc in the same repo, how to structure git submodules
- [x] pop-up about personal experience as well (share & discuss)
- [x] Grouped according to preferences in languages  - question best practices

**Comment by bast** [comment]
Converting the above to check boxes so that I can tick them off.

**Comment by bast** [comment]
I think I have covered these - except the title rename. I think we have a good starting point and from here we create new issues and PRs. Closing.
