### ISSUE TITLE
clarify "simple vs easy"

### ISSUE THREAD

**Issue by rkdarst** [coderefinery/modular-code-development#7]
In the "simple vs easy" graph, I think "simple" and "easy" can be clarified.  maybe "quick and dirty" and "using proper tools" or something?  I instinctively knew what this was supposed to say, but still had to think of what the words meant (in part because I was tired)

**Comment by rkdarst** [comment]
To add to this, label the regions.  E.g.
* set up git (left side of simple)  --> automated testing, fast development (right of simple)
* no git (left of easy)  --> impossible to debug (right side of easy)

**Comment by blankdots** [comment]
I can add to that, that the graph is a bit confusing and can use some rework.

**Comment by bast** [comment]
I plan to rework that. All suggestions welcome. In particular what the confusing part is but I guess the point is that the graph is not self-explaining enough.

**Comment by rkdarst** [comment]
Mainly: "simple" and "easy" both sound like good things.  It's not clear that "easy" means "quick hacks" or "simple" means "take the time to implement it properly".
